spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: Hunter@4343

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        ddl_auto: update
        dialect: org.hibernate.dialect.MySQLDialect


server:
  port: 9090

logging:
  file:
    name: logs/app.log
  level:
    root: DEBUG



